Repository arduino/arduino-language-server, pull requests merged in 2022-08, with the labels that each got.

#130 Bump Windows runner version for build workflow
  .github/workflows/build.yml
Labels: topic: infrastructure, type: imperfection

#129 Add CI workflow to validate Taskfiles
  .github/workflows/check-taskfiles.yml
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#128 Add CI workflow to lint and check formatting of Go code
  .github/workflows/check-go-task.yml
  README.md
  Taskfile.yml
  ls/builder.go
  ls/ls.go
  ls/ls_clang_to_ide.go
  ls/ls_ide_to_clang.go
  ls/lsp_client_clangd.go
  ls/lsp_logger.go
  ls/lsp_server_ide.go
  ls/progress.go
  sourcemapper/ino.go
Labels: type: enhancement, topic: infrastructure

#131 Check markdown
  .github/workflows/check-markdown-task.yml
  .markdown-link-check.json
  .markdownlint.yml
  .markdownlintignore
  README.md
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#132 Add CI workflow to check the license file
  .github/workflows/check-license.yml
  README.md
Labels: type: enhancement, topic: infrastructure

#133 Sync sketch formatter configuration from source
  ls/ls_formatter.go
Labels: type: enhancement
